---
# tasks file for nginx
- name: Install nginx package
  apt:
    name: nginx
    state: present

- name: Unlink the default nginx host config
  command: unlink /etc/nginx/sites-enabled/default

- name: Copy nginx reverse proxy files
## REQUIRED ##

- name: Create symlink to sites-enabled
  command: ln -s /etc/nginx/sites-available/reverse /etc/nginx/sites-enabled/reverse 

- name: Restart service httpd, in all cases
  service:
    name: nginx
    state: restarted
