- name: Install rtorrent
  apt:
    name: rtorrent
    update-cache: yes
    state: present

- name: Copy rtorrent.rc file into home dir
  template:
    src: rtorrent.j2
    dest: /home/{{ rtorrent_user }}/.rtorrent.rc

- name: Create torrent data structure 
  file:
    path: "/srv/{{item}}"
    recurse: yes
    state: directory
  with_items: ["torrent", "torrent/downloads", "torrent/.session"]

- name: Modify ownership and permissions
  command: "{{item}}"
  with_items:
    - chmod 775 -R /srv/torrent
    - chown {{ rtorrent_user }}:{{ rtorrent_group }} -R /srv/torrent
    - chown {{ rtorrent_user }}:{{ rtorrent_group }} -R /home/{{ rtorrent_user }}/.rtorrent.rc

- name: Create rtorrent service
  template:
    src: rtorrent.service.j2
    dest: /etc/systemd/system/rtorrent.service

- name: Enable and start rtorrent service
  command: "{{item}}"
  with_items:
    - systemctl enable rtorrent.service
    - systemctl start rtorrent
