- name: Install curl
  apt: 
    name: curl
    state: present

- name: Install git
  apt: 
    name: git
    state: present


- name: Install make
  apt: 
    name: make
    state: present

- name: Install gcc
  apt: 
    name: gcc
    state: present

- name: Install g++
  apt: 
    name: g++
    state: present

- name: Get nodejs repo
  get_url:
    url: https://deb.nodesource.com/setup_12.x
    dest: /tmp/nodejs-repo.sh
    mode: a+x

- name: Check for existing flood installation
  stat:
    path: /srv/torrent
    register: flood_dir

- name: Checkout flood repo
  git:
    repo: 'https://github.com/jfurrow/flood.git'
    dest: /srv/torrent
  when: flood_dir.stat.exists == false

- name: Copy template config.js to live file
  copy:
    src: /srv/torrent/flood/config.template.js
    dest: /srv/torrent/flood/config.js
    
- name: Install flood npm pkg
  npm:
    path: /srv/torrent/flood

- name: Build flood package
  command: npm --prefix /srv/torrent/flood run build

- name: Change ownership of flood files
  file:
    path: /srv/torrent/flood
    state: directory
    recurse: yes
    owner: "{{ flood_user }}"
    group: "{{ flood_group }}"

- name: Create flood service unit file
  template:
    src: flood.service.j2
    dest: /etc/systemd/system/flood.service

- name: Enable and start flood service
  command: "{{item}}"
  with_items:
    - systemctl enable flood
    - systemctl start flood
